### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by justinnoah** [wmertens/atom-nix#2]
Typically the standard for a package name for syntax highlighting is: language-&lt;language name>. Perhaps change this project to be named language-nix instead of simply nix?

**Comment by wmertens** [comment]
Hmmm… did you have trouble finding this project? I'd rather not go through
all the steps for renaming a project just for purity… I do agree that
atom-language-nix would be a better name.

**Comment by justinnoah** [comment]
Minor trouble since I was looking for a language-nix, but besides that, not really.

**Comment by wmertens** [comment]
Ok in that case, I'll close this. Thanks for bringing it up though.
